# Generated by Django 4.2.1 on 2023-05-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csbs2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg', models.CharField(default='', max_length=10)),
                ('Dm', models.PositiveIntegerField()),
                ('Oops', models.PositiveIntegerField()),
                ('Dbms', models.PositiveIntegerField()),
                ('Os', models.PositiveIntegerField()),
                ('Ds', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Csbs3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg', models.CharField(default='', max_length=10)),
                ('Dm', models.PositiveIntegerField()),
                ('Oops', models.PositiveIntegerField()),
                ('Dbms', models.PositiveIntegerField()),
                ('Os', models.PositiveIntegerField()),
                ('Ds', models.PositiveIntegerField()),
            ],
        ),
    ]
