# Generated by Django 4.2.1 on 2023-05-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_csbs2_csbs3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csbs',
            name='Reg',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='csbs2',
            name='Reg',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='csbs3',
            name='Reg',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
