# Generated by Django 4.2.1 on 2023-05-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_csbs_reg_alter_csbs2_reg_alter_csbs3_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('S1', models.CharField(max_length=10)),
                ('S2', models.CharField(max_length=10)),
                ('S3', models.CharField(max_length=10)),
                ('S4', models.CharField(max_length=10)),
                ('S5', models.CharField(max_length=10)),
                ('Staff', models.CharField(max_length=10)),
            ],
        ),
    ]
